export NODE_TLS_REJECT_UNAUTHORIZED=0;
export SCHEDULE=* * * * *;
export INV_DB_QUERY_SQL=select __INV_DB_QUERY_FIELDS__ from __INV_DB_NAME__;
export INV_DB_QUERY_FIELDS=IP,NAME,PROVISION_STATUS,NODE_TYPE,NODE_DEF,NETWORKFUNCTION,TREE,STABLENET_AGENT,STABLENET_PMAGENT,SERVICES_LIST,SMON_TAG;
export INV_DB_NAME=INVENTORY;
export INV_DB_USER=sunrise;
export INV_DB_PW=oadvice;
export INV_DB_CON=192.168.12.189:1521/ORCL;
export ASM_BASE_URL=https://192.168.12.226/1.0/rest-observer/rest/;
export ASM_TOPO_URL=https://192.168.12.226/1.0/topology/;
export ASM_USER=asm;
export ASM_PASS=asm;
export ASM_TENANT_ID=cfd95b7e-3bc7-4006-a4a8-a73a79c71255;
export ASM_EP_JOB_ID=snr_inventory;
export ASM_EP_RES=resources;
export ASM_EP_RES_FLT=?_filter=entityTypes%3DnetworkDevice&_field=name&_include_global_resources=false&_include_count=false&_include_status=false&_include_status_severity=false&_include_metadata=false&_return_composites=true;
export TZ=Europe/Berlin;
export DELETE_IF_NOT_PRESENT_IN_INV=true;
export ASM_EP_RES_DEL_IMMEDIATE=true;
export ASM_EP_DEL_WAIT_TIME_MS=6000;
export ASM_EP_RES_DEL_IMMEDIATE_PARAM=?_immediate=true;
export ASM_ENTITY_TYPE=networkDevice;